name: My First Action

on:
  workflow_dispatch:

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: List files
        run: ls -la

      - name: Read file
        run: cat Santosh.txt
